// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SHAZ_CharacterAnchor","status":true,"description":"Adjust anchor positions to change alignment with tiles.","parameters":{}},
{"name":"TDDP_PixelPerfect","status":true,"description":"1.1.1 Enable pixel perfect scaling mode for your game","parameters":{"enableIngameOptions":"false","labels":"","en":"Pixel Perfect Mode","ja":"ピクセルパーフェクトモード","zh":"像素完美模式","ko":"픽셀 퍼펙트 모드","ru":"Режим Pixel Perfect"}},
{"name":"SPACE_LIT12","status":true,"description":"Permit use of _originalPattern for non-event characters.","parameters":{}},
{"name":"GALV_MessageBustsMZ","status":true,"description":"(v.1.2) Displays a bust image instead of selected face image","parameters":{"bPriority":"0","bPosition":"0","bX":"0","bY":"104","xOffset":"0","fileAppend":"_bust","mStyleBusts":"false"}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"GALV_CharacterAnimationsMZ","status":true,"description":"(v.1.3) Make the player and follower characters use different\ngraphics for idle, walk and run. View HELP for more info.","parameters":{"useJumpGraphic":"true","vehicles":"false","commonEventId":"0","commonEventTime":"0","repeatCommonEvent":"true"}}
];
