// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PKD_FontsManager","status":true,"description":"(v.1.0)[BASIC] Fonts Manager - custom fonts and colors","parameters":{"fontsToLoad:strA":"[\"Anthony Hunter.ttf\",\"Catalish Huntera Italic.ttf\",\"Delinda Agatha.ttf\",\"Gemini Moon.otf\"]","isGlobal:b":"true","isAutoLoad:b":"false","spacer|defaultFonts":"","defaultSetup":"","allItemsFont":"","allArmorsFont":"","allWeaponsFont":"","allSkillsFont":"","allActorNamesFont":"","allActorClassFont":"","allActorNickFont":"","allActorLevelFont":"","spacer|colors":"","pallete:strA":"[\"#c149e2\",\"#13675f\",\"#b2c05d\"]","userPalletes:structA":"[]","isGlobalColors:b":"true","spacer|endHolder":""}},
{"name":"GALV_CharacterAnimationsMZ","status":true,"description":"(v.1.3) Make the player and follower characters use different\r\ngraphics for idle, walk and run. View HELP for more info.","parameters":{"useJumpGraphic":"true","vehicles":"false","commonEventId":"0","commonEventTime":"0","repeatCommonEvent":"true"}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}}
];
